#include "Arduino.h"
#include "single_emag_shutter_controll.h"
#include "hwconf.h"
#include "stdint.h"
#include "BLE_handler.h"
#include <BLEDevice.h>
#include <BLEUtils.h>
#include <BLEScan.h>
#include <BLEAdvertisedDevice.h>
#include "main.h"
#include <Preferences.h>